version: "3.9"

services:
  flask_app:
    container_name: eikon_app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    networks:
      - default
    volumes:
      - .:/eikon
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=eikon
    networks:
      - default
    volumes:
      - ./src/db/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
